//
//  ListWorker.swift
//  testTask
//
//  Created by Mac on 4/27/18.
//  Copyright (c) 2018 kovtuns. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListWorker {
    func getSearchResult(request: List.Model.Request, _ completion: @escaping ([String : Any]?, Error?)->()){
        RequestManager.sharedInstance.getSearchList(term: request.term ?? "", media: request.media ?? "", completion)
    }
}
